version: '3.4'


services:  
    bulkyweb:    
      image: ${DOCKER_REGISTRY-}bulkyweb    
      build:      
        context: .      
        dockerfile: BulkyWeb/Dockerfile
      environment:
        - ConnectionStrings:Bulky_CON_COM=Server=sqlserver;Database=Bulky;User ID=sa;Password=${Bulky_Pass};Connect Timeout=30;Encrypt=False;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False;
      secrets:
        - Bulky_Pass
      depends_on:      
        - sqlserver  
       
    sqlserver:    
      image: mcr.microsoft.com/mssql/server:2022-latest    
      environment:      
        SA_PASSWORD: ${Bulky_Pass}
        ACCEPT_EULA: "Y"    
      secrets:
        - Bulky_Pass
      ports:      
        - "1433:1433"    
      volumes:      
        - C:/DockerVolumes/BulkyMsSql/data:/var/opt/mssql/data      
        - C:/DockerVolumes/BulkyMsSql/log:/var/opt/mssql/log      
        - C:/DockerVolumes/BulkyMsSql/secrets:/var/opt/mssql/secrets      

secrets:
  Bulky_Pass:
    file: db_passwrd.txt

volumes:
  Bulky_VOL:
        